//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_Talyzenkov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Strahovka = new HashSet<Strahovka>();
        }
    
        public int id_car { get; set; }
        public string Moshnost { get; set; }
        public string Obiom { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string God_Vipuska { get; set; }
        public string VIN { get; set; }
        public string Image { get; set; }
        public string Number_PTS { get; set; }
        public string Gos_Znak { get; set; }
        public string Color { get; set; }
        public int id_Owner { get; set; }
        public string Img
        {
            get
            {
                return "/Resources/" + Image;
            }
        }

        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strahovka> Strahovka { get; set; }
    }
}
