//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_Talyzenkov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.Cars = new HashSet<Cars>();
            this.Shtraf_Protokol = new HashSet<Shtraf_Protokol>();
        }
    
        public int id_Owner { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Otshestvo { get; set; }
        public System.DateTime Date_Rozdenia { get; set; }
        public string Gorod_Prozivania { get; set; }
        public string Ylitsa { get; set; }
        public Nullable<int> Number_Doma { get; set; }
        public string login { get; set; }
        public string Password { get; set; }
        public int id_Role { get; set; }
        public string Foto { get; set; }
        public int Number_Prav { get; set; }
        public int Id_Strahovka { get; set; }
        public string ImgFoto
        {
            get
            {
                return "/Resources/" + Foto;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual Num_Prav Num_Prav { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shtraf_Protokol> Shtraf_Protokol { get; set; }
        public virtual Strahovka Strahovka { get; set; }
    }
}
