//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_Talyzenkov.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shtraf_Protokol
    {
        public int id_Protokol { get; set; }
        public int id_Owner { get; set; }
        public System.DateTime Date_Narushenia { get; set; }
        public string Mesto_Narushenia { get; set; }
        public string Syshnost_Narushenia { get; set; }
        public string Summa_Shtrafa { get; set; }
        public string Lishenie { get; set; }
        public System.DateTime Date_Oplati { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
